<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18426" started-at="2020-05-12T04:07:17Z" finished-at="2020-05-12T04:07:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18426" started-at="2020-05-12T04:07:17Z" finished-at="2020-05-12T04:07:36Z">
      <class name="com.acti.TestCase.TestLoginSS">
        <test-method status="PASS" signature="Reports()[pri:0, instance:com.acti.TestCase.TestLoginSS@3532ec19]" name="Reports" is-config="true" duration-ms="443" started-at="2020-05-11T21:07:17Z" finished-at="2020-05-11T21:07:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reports -->
        <test-method status="PASS" signature="PageStart()[pri:0, instance:com.acti.TestCase.TestLoginSS@3532ec19]" name="PageStart" is-config="true" duration-ms="15265" started-at="2020-05-11T21:07:18Z" finished-at="2020-05-11T21:07:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PageStart -->
        <test-method status="FAIL" signature="SSTest()[pri:0, instance:com.acti.TestCase.TestLoginSS@3532ec19]" name="SSTest" duration-ms="666" started-at="2020-05-11T21:07:33Z" finished-at="2020-05-11T21:07:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.acti.TestCase.TestLoginSS.SSTest(TestLoginSS.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SSTest -->
        <test-method status="PASS" signature="ScreenShotBase(org.testng.ITestResult)[pri:0, instance:com.acti.TestCase.TestLoginSS@3532ec19]" name="ScreenShotBase" is-config="true" duration-ms="2005" started-at="2020-05-11T21:07:34Z" finished-at="2020-05-11T21:07:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=SSTest status=FAILURE method=TestLoginSS.SSTest()[pri:0, instance:com.acti.TestCase.TestLoginSS@3532ec19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ScreenShotBase -->
      </class> <!-- com.acti.TestCase.TestLoginSS -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
